# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: contact.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='contact.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rcontact.proto\"A\n\x11\x41\x64\x64\x46orwardRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\r\n\x05token\x18\x03 \x01(\t\"D\n\x14RemoveForwardRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\r\n\x05token\x18\x03 \x01(\t\"%\n\x12\x41\x64\x64\x46orwardResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"(\n\x15RemoveForwardResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x89\x01\n\x0c\x41lterForward\x12\x37\n\nAddForward\x12\x12.AddForwardRequest\x1a\x13.AddForwardResponse\"\x00\x12@\n\rRemoveForward\x12\x15.RemoveForwardRequest\x1a\x16.RemoveForwardResponse\"\x00\x62\x06proto3'
)




_ADDFORWARDREQUEST = _descriptor.Descriptor(
  name='AddForwardRequest',
  full_name='AddForwardRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='AddForwardRequest.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='AddForwardRequest.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token', full_name='AddForwardRequest.token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=82,
)


_REMOVEFORWARDREQUEST = _descriptor.Descriptor(
  name='RemoveForwardRequest',
  full_name='RemoveForwardRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='RemoveForwardRequest.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='RemoveForwardRequest.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token', full_name='RemoveForwardRequest.token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=152,
)


_ADDFORWARDRESPONSE = _descriptor.Descriptor(
  name='AddForwardResponse',
  full_name='AddForwardResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='AddForwardResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=191,
)


_REMOVEFORWARDRESPONSE = _descriptor.Descriptor(
  name='RemoveForwardResponse',
  full_name='RemoveForwardResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='RemoveForwardResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=233,
)

DESCRIPTOR.message_types_by_name['AddForwardRequest'] = _ADDFORWARDREQUEST
DESCRIPTOR.message_types_by_name['RemoveForwardRequest'] = _REMOVEFORWARDREQUEST
DESCRIPTOR.message_types_by_name['AddForwardResponse'] = _ADDFORWARDRESPONSE
DESCRIPTOR.message_types_by_name['RemoveForwardResponse'] = _REMOVEFORWARDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AddForwardRequest = _reflection.GeneratedProtocolMessageType('AddForwardRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDFORWARDREQUEST,
  '__module__' : 'contact_pb2'
  # @@protoc_insertion_point(class_scope:AddForwardRequest)
  })
_sym_db.RegisterMessage(AddForwardRequest)

RemoveForwardRequest = _reflection.GeneratedProtocolMessageType('RemoveForwardRequest', (_message.Message,), {
  'DESCRIPTOR' : _REMOVEFORWARDREQUEST,
  '__module__' : 'contact_pb2'
  # @@protoc_insertion_point(class_scope:RemoveForwardRequest)
  })
_sym_db.RegisterMessage(RemoveForwardRequest)

AddForwardResponse = _reflection.GeneratedProtocolMessageType('AddForwardResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDFORWARDRESPONSE,
  '__module__' : 'contact_pb2'
  # @@protoc_insertion_point(class_scope:AddForwardResponse)
  })
_sym_db.RegisterMessage(AddForwardResponse)

RemoveForwardResponse = _reflection.GeneratedProtocolMessageType('RemoveForwardResponse', (_message.Message,), {
  'DESCRIPTOR' : _REMOVEFORWARDRESPONSE,
  '__module__' : 'contact_pb2'
  # @@protoc_insertion_point(class_scope:RemoveForwardResponse)
  })
_sym_db.RegisterMessage(RemoveForwardResponse)



_ALTERFORWARD = _descriptor.ServiceDescriptor(
  name='AlterForward',
  full_name='AlterForward',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=236,
  serialized_end=373,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddForward',
    full_name='AlterForward.AddForward',
    index=0,
    containing_service=None,
    input_type=_ADDFORWARDREQUEST,
    output_type=_ADDFORWARDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='RemoveForward',
    full_name='AlterForward.RemoveForward',
    index=1,
    containing_service=None,
    input_type=_REMOVEFORWARDREQUEST,
    output_type=_REMOVEFORWARDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ALTERFORWARD)

DESCRIPTOR.services_by_name['AlterForward'] = _ALTERFORWARD

# @@protoc_insertion_point(module_scope)
