# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import contact_pb2 as contact__pb2


class AlterForwardStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddForward = channel.unary_unary(
                '/AlterForward/AddForward',
                request_serializer=contact__pb2.AddForwardRequest.SerializeToString,
                response_deserializer=contact__pb2.AddForwardResponse.FromString,
                )
        self.RemoveForward = channel.unary_unary(
                '/AlterForward/RemoveForward',
                request_serializer=contact__pb2.RemoveForwardRequest.SerializeToString,
                response_deserializer=contact__pb2.RemoveForwardResponse.FromString,
                )


class AlterForwardServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddForward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveForward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AlterForwardServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddForward': grpc.unary_unary_rpc_method_handler(
                    servicer.AddForward,
                    request_deserializer=contact__pb2.AddForwardRequest.FromString,
                    response_serializer=contact__pb2.AddForwardResponse.SerializeToString,
            ),
            'RemoveForward': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveForward,
                    request_deserializer=contact__pb2.RemoveForwardRequest.FromString,
                    response_serializer=contact__pb2.RemoveForwardResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AlterForward', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AlterForward(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddForward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AlterForward/AddForward',
            contact__pb2.AddForwardRequest.SerializeToString,
            contact__pb2.AddForwardResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RemoveForward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AlterForward/RemoveForward',
            contact__pb2.RemoveForwardRequest.SerializeToString,
            contact__pb2.RemoveForwardResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
